/* Generated By:JavaCC: Do not edit this line. HelloConstants.java */
package team;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int create = 5;
  /** RegularExpression Id. */
  int alphanumeric = 6;
  /** RegularExpression Id. */
  int TEXT = 7;
  /** RegularExpression Id. */
  int decoratedText = 8;
  /** RegularExpression Id. */
  int color = 9;
  /** RegularExpression Id. */
  int font = 10;
  /** RegularExpression Id. */
  int link = 11;
  /** RegularExpression Id. */
  int quote = 12;
  /** RegularExpression Id. */
  int and = 13;
  /** RegularExpression Id. */
  int NULL = 14;
  /** RegularExpression Id. */
  int sentence = 15;
  /** RegularExpression Id. */
  int ELEMENT = 16;
  /** RegularExpression Id. */
  int quotation = 17;
  /** RegularExpression Id. */
  int IMAGE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<create>",
    "<alphanumeric>",
    "<TEXT>",
    "<decoratedText>",
    "<color>",
    "<font>",
    "<link>",
    "\"\\\"\"",
    "\"AND\"",
    "\"null\"",
    "<sentence>",
    "<ELEMENT>",
    "<quotation>",
    "<IMAGE>",
  };

}
